---
 
ENV: 'qa'
TYPE: 'hotpatch'
AWS_ACCOUNT_ID: '55136349XXXX'
irm_scripts_folder: '/app/orm/scripts/irm/'
 
# AWS specific variables
JAVA_HOME: '/usr/lib/jvm/jre'
AWS_CREDENTIAL_FILE: '/root/.awscredentials'
AWS_DEFAULT_OUTPUT: 'table'
EC2_HOME: '/usr/local/ec2-api-tools'
AWS_RDS_HOME: '/usr/local/rds-api-tools'
AWS_AUTO_SCALING_HOME: '/usr/local/as-api-tools'
AWS_ELB_HOME: '/usr/local/elb-api-tools'
AWS_CLOUDWATCH_HOME: '/usr/local/mon-api-tools'
AWS_IAM_HOME: '/usr/local/iam-api-tools'
PATH: '{{ AWS_AUTO_SCALING_HOME }}/bin:{{ AWS_RDS_HOME }}/bin:{{ AWS_ELB_HOME }}/bin:{{ EC2_HOME }}/bin:{{ AWS_CLOUDWATCH_HOME }}/bin:{{ AWS_IAM_HOME }}/bin'
aws_instance: 'i-0f1172cf93cc1abfb'
instance_tag: 'orm-us-east-1-prod-frontend-main'
 
# SVN specific variables
svn_url: 'svn://182.72.188.28/home/svndata/fontis-test/'
svn_user: 'ndatta'
svn_password: '!@#ndatta'
current_svn_tag: 'ORM 5.3.9.24'
new_svn_tag: 'ORM 5.3.9.24'
 
# MYSQL specific variables
mysql_path: ''
mysql_port: '3306'
mysql_user: 'fsrmcron'
mysql_password: 'FDxm2X76'
ssl_cert: '/home/pem/mysql-ssl-ca-cert.pem'
 
# RDS specific variables
rds_name: 'orm-us-east-1-prod-db'
rds_host: 'orm-us-east-1-prod-db.cwc04xnt1ovy.us-east-1.rds.amazonaws.com'
 
# App specific variables
domainName: 'igpolicy.net'
www_root: '/var/www/www.igpolicy.net'
platform_type: 'PROD'
svn_repo_folder: 'repository'
current_tag: '5.2.0.18_0'
current_tag_int: '105102100118100'
current_rev: '21256'
time_stamp: '2017-03-27_1490614229'
tag_name: 'fontis-env'
app_name: 'Policy Center'
current_svn_tag_clean: 'ORM '
 
# Deployment specific variables
aws_region: 'us-east-1'
instance_tag: 'orm-us-east-1-poc'
security_group: 'sg-91d4f2ea'
security_group_backend: 'sg-8fdbfdf4'
preloaded_backend_ssh_key: 'us-irm-qa'
sources_update: 'y'
def_sources_update: 'y'
def_sources_update_f: 'y'
sources_update_co: 'y'
def_sources_update_co: 'n'
def_sources_update_co_f: 'y'
db_update: 'n'
def_db_update: 'n'
def_db_update_f: 'n'
destroy_platform: 'n'
def_destroy_platform: 'n'
def_destroy_platform_f: 'n'
recreate_platform: 'n'
def_recreate_platform: 'n'
def_recreate_platform_f: 'n'
destroy_main_backend: 'n'
def_destroy_main_backend: 'n'
def_destroy_main_backend_f: 'n'
destroy_itself: 'n'
def_destroy_itself: 'n'
def_destroy_itself_f: 'n'
create_ami: 'y'
def_create_ami: 'y'
def_create_ami_f: 'y'
destroy_old_ami: 'y'
def_destroy_old_ami: 'y'
def_destroy_old_ami_f: 'y'
overwrite_as_group_name: 'n'
def_overwrite_as_group_name: 'n'
def_overwrite_as_group_name_f: 'n'
instance_type: 'm3.xlarge'
instance_type_backend: 'm3.xlarge'
instance_type_backend_main: 'm3.xlarge'
load_balancer_name: 'Fontis-Ansible-Test-elb'
as_launch_config_name: '{{ instance_tag }}'
mon_alarm_suffix: '{{ as_launch_config_name }}-alarm'
addpolicy_name: '{{ as_launch_config_name }}-addpolicy'
delpolicy_name: '{{ as_launch_config_name }}-delpolicy'
latencyscaleup_alarm_name: '{{ as_launch_config_name }}-alarm-latencyscaleup'
unhealthyscaleup_alarm_name: '{{ as_launch_config_name }}-alarm-unhealthyscaleup'
cpuscaledown_alarm_name: '{{ as_launch_config_name }}-alarm-cpuscaledown'
sqsscaleup_alarm_name: '{{ as_launch_config_name }}-alarm-sqsscaleup'
min_size_frontend: '1'
min_size_backend: '0'
max_size_frontend: '3'
max_size_backend: '10'
desired_capacity: '1'
unhealthy_threshold: '20'
as_zones_a: '{{ aws_region }}a'
as_zones_c: '{{ aws_region }}c'
as_zones_backend_a: '{{ aws_region }}a'
as_zones_backend_c: '{{ aws_region }}c'
as_grace_period: '300'
as_cooldown_default: '300'
as_cooldown_frontend: '500'
as_cooldown_backend: '500'
reports_alarm_comparison_op: 'GreaterThanThreshold'
stop_frontend_main: 'n'
def_stop_frontend_main: 'n'
def_stop_frontend_main_f: 'n'
money_saving_platform: 'n'
as_group_name: 'us-east-1-qa-group'
 
 
# CDN specific variables
cdn_domain_var: 'https://d29mcjn5i2toiy.cloudfront.net'
 
# VPC specific variables
frontendVPC: 'subnet-1efcdc46,subnet-fa092fd0'
backendVPC: 'subnet-1efcdc46,subnet-fa092fd0'
backendVPC_main: 'subnet-1efcdc46'
CLfrontendSecurityGroupVPC: 'us-qa-orm-frontend-main'
CLbackendSecurityGroupVPC: 'us-qa-orm-backend-main'
frontendVPCID: 'vpc-b75bdfd0'
backendVPCID: 'vpc-b75bdfd0'

