---

- hosts: FONTISTEST

  vars:
    aws_env:
      AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY') }}"
      AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_KEY') }}"
      AWS_DEFAULT_REGION: "{{ AWS_DEFAULT_REGION }}"

  roles:
    - do_deployment

